// Code generated by protoc-gen-go. DO NOT EDIT.
// source: clservice.proto

package pb

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type NewClientRequest struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Birthday             int64    `protobuf:"varint,2,opt,name=birthday,proto3" json:"birthday,omitempty"`
	Score                int64    `protobuf:"varint,3,opt,name=score,proto3" json:"score,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NewClientRequest) Reset()         { *m = NewClientRequest{} }
func (m *NewClientRequest) String() string { return proto.CompactTextString(m) }
func (*NewClientRequest) ProtoMessage()    {}
func (*NewClientRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_1b09ac349de90e68, []int{0}
}

func (m *NewClientRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NewClientRequest.Unmarshal(m, b)
}
func (m *NewClientRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NewClientRequest.Marshal(b, m, deterministic)
}
func (m *NewClientRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NewClientRequest.Merge(m, src)
}
func (m *NewClientRequest) XXX_Size() int {
	return xxx_messageInfo_NewClientRequest.Size(m)
}
func (m *NewClientRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_NewClientRequest.DiscardUnknown(m)
}

var xxx_messageInfo_NewClientRequest proto.InternalMessageInfo

func (m *NewClientRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *NewClientRequest) GetBirthday() int64 {
	if m != nil {
		return m.Birthday
	}
	return 0
}

func (m *NewClientRequest) GetScore() int64 {
	if m != nil {
		return m.Score
	}
	return 0
}

type NewClientResponse struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NewClientResponse) Reset()         { *m = NewClientResponse{} }
func (m *NewClientResponse) String() string { return proto.CompactTextString(m) }
func (*NewClientResponse) ProtoMessage()    {}
func (*NewClientResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_1b09ac349de90e68, []int{1}
}

func (m *NewClientResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NewClientResponse.Unmarshal(m, b)
}
func (m *NewClientResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NewClientResponse.Marshal(b, m, deterministic)
}
func (m *NewClientResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NewClientResponse.Merge(m, src)
}
func (m *NewClientResponse) XXX_Size() int {
	return xxx_messageInfo_NewClientResponse.Size(m)
}
func (m *NewClientResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_NewClientResponse.DiscardUnknown(m)
}

var xxx_messageInfo_NewClientResponse proto.InternalMessageInfo

func (m *NewClientResponse) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type QueryClientsRequest struct {
	Id       *OptString `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name     *OptString `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Birthday *Int64Comp `protobuf:"bytes,3,opt,name=birthday,proto3" json:"birthday,omitempty"`
	Score    *Int64Comp `protobuf:"bytes,4,opt,name=score,proto3" json:"score,omitempty"`
	CreatedAt            *Int64Comp `protobuf:"bytes,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *QueryClientsRequest) Reset()         { *m = QueryClientsRequest{} }
func (m *QueryClientsRequest) String() string { return proto.CompactTextString(m) }
func (*QueryClientsRequest) ProtoMessage()    {}
func (*QueryClientsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_1b09ac349de90e68, []int{2}
}

func (m *QueryClientsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_QueryClientsRequest.Unmarshal(m, b)
}
func (m *QueryClientsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_QueryClientsRequest.Marshal(b, m, deterministic)
}
func (m *QueryClientsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryClientsRequest.Merge(m, src)
}
func (m *QueryClientsRequest) XXX_Size() int {
	return xxx_messageInfo_QueryClientsRequest.Size(m)
}
func (m *QueryClientsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryClientsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryClientsRequest proto.InternalMessageInfo

func (m *QueryClientsRequest) GetId() *OptString {
	if m != nil {
		return m.Id
	}
	return nil
}

func (m *QueryClientsRequest) GetName() *OptString {
	if m != nil {
		return m.Name
	}
	return nil
}

func (m *QueryClientsRequest) GetBirthday() *Int64Comp {
	if m != nil {
		return m.Birthday
	}
	return nil
}

func (m *QueryClientsRequest) GetScore() *Int64Comp {
	if m != nil {
		return m.Score
	}
	return nil
}

func (m *QueryClientsRequest) GetCreatedAt() *Int64Comp {
	if m != nil {
		return m.CreatedAt
	}
	return nil
}

type QueryClientsResponse struct {
	Ids                  []string `protobuf:"bytes,1,rep,name=ids,proto3" json:"ids,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *QueryClientsResponse) Reset()         { *m = QueryClientsResponse{} }
func (m *QueryClientsResponse) String() string { return proto.CompactTextString(m) }
func (*QueryClientsResponse) ProtoMessage()    {}
func (*QueryClientsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_1b09ac349de90e68, []int{3}
}

func (m *QueryClientsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_QueryClientsResponse.Unmarshal(m, b)
}
func (m *QueryClientsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_QueryClientsResponse.Marshal(b, m, deterministic)
}
func (m *QueryClientsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryClientsResponse.Merge(m, src)
}
func (m *QueryClientsResponse) XXX_Size() int {
	return xxx_messageInfo_QueryClientsResponse.Size(m)
}
func (m *QueryClientsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryClientsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryClientsResponse proto.InternalMessageInfo

func (m *QueryClientsResponse) GetIds() []string {
	if m != nil {
		return m.Ids
	}
	return nil
}

type GetClientsRequest struct {
	Ids                  []string `protobuf:"bytes,1,rep,name=ids,proto3" json:"ids,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetClientsRequest) Reset()         { *m = GetClientsRequest{} }
func (m *GetClientsRequest) String() string { return proto.CompactTextString(m) }
func (*GetClientsRequest) ProtoMessage()    {}
func (*GetClientsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_1b09ac349de90e68, []int{4}
}

func (m *GetClientsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetClientsRequest.Unmarshal(m, b)
}
func (m *GetClientsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetClientsRequest.Marshal(b, m, deterministic)
}
func (m *GetClientsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetClientsRequest.Merge(m, src)
}
func (m *GetClientsRequest) XXX_Size() int {
	return xxx_messageInfo_GetClientsRequest.Size(m)
}
func (m *GetClientsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetClientsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetClientsRequest proto.InternalMessageInfo

func (m *GetClientsRequest) GetIds() []string {
	if m != nil {
		return m.Ids
	}
	return nil
}

type GetClientsResponse struct {
	Clients              []*Client `protobuf:"bytes,1,rep,name=clients,proto3" json:"clients,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *GetClientsResponse) Reset()         { *m = GetClientsResponse{} }
func (m *GetClientsResponse) String() string { return proto.CompactTextString(m) }
func (*GetClientsResponse) ProtoMessage()    {}
func (*GetClientsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_1b09ac349de90e68, []int{5}
}

func (m *GetClientsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetClientsResponse.Unmarshal(m, b)
}
func (m *GetClientsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetClientsResponse.Marshal(b, m, deterministic)
}
func (m *GetClientsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetClientsResponse.Merge(m, src)
}
func (m *GetClientsResponse) XXX_Size() int {
	return xxx_messageInfo_GetClientsResponse.Size(m)
}
func (m *GetClientsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetClientsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetClientsResponse proto.InternalMessageInfo

func (m *GetClientsResponse) GetClients() []*Client {
	if m != nil {
		return m.Clients
	}
	return nil
}

type DeleteClientRequest struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteClientRequest) Reset()         { *m = DeleteClientRequest{} }
func (m *DeleteClientRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteClientRequest) ProtoMessage()    {}
func (*DeleteClientRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_1b09ac349de90e68, []int{6}
}

func (m *DeleteClientRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteClientRequest.Unmarshal(m, b)
}
func (m *DeleteClientRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteClientRequest.Marshal(b, m, deterministic)
}
func (m *DeleteClientRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteClientRequest.Merge(m, src)
}
func (m *DeleteClientRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteClientRequest.Size(m)
}
func (m *DeleteClientRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteClientRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteClientRequest proto.InternalMessageInfo

func (m *DeleteClientRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type DeleteClientResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteClientResponse) Reset()         { *m = DeleteClientResponse{} }
func (m *DeleteClientResponse) String() string { return proto.CompactTextString(m) }
func (*DeleteClientResponse) ProtoMessage()    {}
func (*DeleteClientResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_1b09ac349de90e68, []int{7}
}

func (m *DeleteClientResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteClientResponse.Unmarshal(m, b)
}
func (m *DeleteClientResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteClientResponse.Marshal(b, m, deterministic)
}
func (m *DeleteClientResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteClientResponse.Merge(m, src)
}
func (m *DeleteClientResponse) XXX_Size() int {
	return xxx_messageInfo_DeleteClientResponse.Size(m)
}
func (m *DeleteClientResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteClientResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteClientResponse proto.InternalMessageInfo

type DeleteAllClientsRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteAllClientsRequest) Reset()         { *m = DeleteAllClientsRequest{} }
func (m *DeleteAllClientsRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteAllClientsRequest) ProtoMessage()    {}
func (*DeleteAllClientsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_1b09ac349de90e68, []int{8}
}

func (m *DeleteAllClientsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteAllClientsRequest.Unmarshal(m, b)
}
func (m *DeleteAllClientsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteAllClientsRequest.Marshal(b, m, deterministic)
}
func (m *DeleteAllClientsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteAllClientsRequest.Merge(m, src)
}
func (m *DeleteAllClientsRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteAllClientsRequest.Size(m)
}
func (m *DeleteAllClientsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteAllClientsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteAllClientsRequest proto.InternalMessageInfo

type DeleteAllClientsResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteAllClientsResponse) Reset()         { *m = DeleteAllClientsResponse{} }
func (m *DeleteAllClientsResponse) String() string { return proto.CompactTextString(m) }
func (*DeleteAllClientsResponse) ProtoMessage()    {}
func (*DeleteAllClientsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_1b09ac349de90e68, []int{9}
}

func (m *DeleteAllClientsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteAllClientsResponse.Unmarshal(m, b)
}
func (m *DeleteAllClientsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteAllClientsResponse.Marshal(b, m, deterministic)
}
func (m *DeleteAllClientsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteAllClientsResponse.Merge(m, src)
}
func (m *DeleteAllClientsResponse) XXX_Size() int {
	return xxx_messageInfo_DeleteAllClientsResponse.Size(m)
}
func (m *DeleteAllClientsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteAllClientsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteAllClientsResponse proto.InternalMessageInfo

type NewMatchRequest struct {
	ClientId             string   `protobuf:"bytes,1,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	Score                int64    `protobuf:"varint,2,opt,name=score,proto3" json:"score,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NewMatchRequest) Reset()         { *m = NewMatchRequest{} }
func (m *NewMatchRequest) String() string { return proto.CompactTextString(m) }
func (*NewMatchRequest) ProtoMessage()    {}
func (*NewMatchRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_1b09ac349de90e68, []int{10}
}

func (m *NewMatchRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NewMatchRequest.Unmarshal(m, b)
}
func (m *NewMatchRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NewMatchRequest.Marshal(b, m, deterministic)
}
func (m *NewMatchRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NewMatchRequest.Merge(m, src)
}
func (m *NewMatchRequest) XXX_Size() int {
	return xxx_messageInfo_NewMatchRequest.Size(m)
}
func (m *NewMatchRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_NewMatchRequest.DiscardUnknown(m)
}

var xxx_messageInfo_NewMatchRequest proto.InternalMessageInfo

func (m *NewMatchRequest) GetClientId() string {
	if m != nil {
		return m.ClientId
	}
	return ""
}

func (m *NewMatchRequest) GetScore() int64 {
	if m != nil {
		return m.Score
	}
	return 0
}

type NewMatchResponse struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NewMatchResponse) Reset()         { *m = NewMatchResponse{} }
func (m *NewMatchResponse) String() string { return proto.CompactTextString(m) }
func (*NewMatchResponse) ProtoMessage()    {}
func (*NewMatchResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_1b09ac349de90e68, []int{11}
}

func (m *NewMatchResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NewMatchResponse.Unmarshal(m, b)
}
func (m *NewMatchResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NewMatchResponse.Marshal(b, m, deterministic)
}
func (m *NewMatchResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NewMatchResponse.Merge(m, src)
}
func (m *NewMatchResponse) XXX_Size() int {
	return xxx_messageInfo_NewMatchResponse.Size(m)
}
func (m *NewMatchResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_NewMatchResponse.DiscardUnknown(m)
}

var xxx_messageInfo_NewMatchResponse proto.InternalMessageInfo

func (m *NewMatchResponse) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

type SortRequest struct {
	Items                []string `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	RemoveDuplicates     bool     `protobuf:"varint,2,opt,name=remove_duplicates,json=removeDuplicates,proto3" json:"remove_duplicates,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SortRequest) Reset()         { *m = SortRequest{} }
func (m *SortRequest) String() string { return proto.CompactTextString(m) }
func (*SortRequest) ProtoMessage()    {}
func (*SortRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_1b09ac349de90e68, []int{12}
}

func (m *SortRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SortRequest.Unmarshal(m, b)
}
func (m *SortRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SortRequest.Marshal(b, m, deterministic)
}
func (m *SortRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SortRequest.Merge(m, src)
}
func (m *SortRequest) XXX_Size() int {
	return xxx_messageInfo_SortRequest.Size(m)
}
func (m *SortRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SortRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SortRequest proto.InternalMessageInfo

func (m *SortRequest) GetItems() []string {
	if m != nil {
		return m.Items
	}
	return nil
}

func (m *SortRequest) GetRemoveDuplicates() bool {
	if m != nil {
		return m.RemoveDuplicates
	}
	return false
}

type SortResponse struct {
	Items                []string `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SortResponse) Reset()         { *m = SortResponse{} }
func (m *SortResponse) String() string { return proto.CompactTextString(m) }
func (*SortResponse) ProtoMessage()    {}
func (*SortResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_1b09ac349de90e68, []int{13}
}

func (m *SortResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SortResponse.Unmarshal(m, b)
}
func (m *SortResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SortResponse.Marshal(b, m, deterministic)
}
func (m *SortResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SortResponse.Merge(m, src)
}
func (m *SortResponse) XXX_Size() int {
	return xxx_messageInfo_SortResponse.Size(m)
}
func (m *SortResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SortResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SortResponse proto.InternalMessageInfo

func (m *SortResponse) GetItems() []string {
	if m != nil {
		return m.Items
	}
	return nil
}

func init() {
	proto.RegisterType((*NewClientRequest)(nil), "pb.NewClientRequest")
	proto.RegisterType((*NewClientResponse)(nil), "pb.NewClientResponse")
	proto.RegisterType((*QueryClientsRequest)(nil), "pb.QueryClientsRequest")
	proto.RegisterType((*QueryClientsResponse)(nil), "pb.QueryClientsResponse")
	proto.RegisterType((*GetClientsRequest)(nil), "pb.GetClientsRequest")
	proto.RegisterType((*GetClientsResponse)(nil), "pb.GetClientsResponse")
	proto.RegisterType((*DeleteClientRequest)(nil), "pb.DeleteClientRequest")
	proto.RegisterType((*DeleteClientResponse)(nil), "pb.DeleteClientResponse")
	proto.RegisterType((*DeleteAllClientsRequest)(nil), "pb.DeleteAllClientsRequest")
	proto.RegisterType((*DeleteAllClientsResponse)(nil), "pb.DeleteAllClientsResponse")
	proto.RegisterType((*NewMatchRequest)(nil), "pb.NewMatchRequest")
	proto.RegisterType((*NewMatchResponse)(nil), "pb.NewMatchResponse")
	proto.RegisterType((*SortRequest)(nil), "pb.SortRequest")
	proto.RegisterType((*SortResponse)(nil), "pb.SortResponse")
}

func init() { proto.RegisterFile("clservice.proto", fileDescriptor_1b09ac349de90e68) }

var fileDescriptor_1b09ac349de90e68 = []byte{
	// 590 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x54, 0x5d, 0x6f, 0xda, 0x30,
	0x14, 0x2d, 0x49, 0xbb, 0xc1, 0xed, 0x07, 0x60, 0xb2, 0x36, 0x4b, 0x37, 0x89, 0xa5, 0xad, 0xc4,
	0xd4, 0x0d, 0x24, 0xba, 0x0f, 0xa9, 0xd2, 0x1e, 0x3a, 0x90, 0xa6, 0x3e, 0xac, 0xdd, 0xe0, 0x65,
	0xda, 0x0b, 0xca, 0xc7, 0x15, 0x58, 0x0a, 0x49, 0x16, 0x1b, 0x2a, 0xfe, 0xe3, 0x5e, 0xf7, 0x7f,
	0xa6, 0xc4, 0x4e, 0x08, 0x49, 0xde, 0xe2, 0x73, 0x8f, 0xcf, 0x3d, 0xd7, 0x3e, 0x0e, 0x34, 0x1d,
	0x8f, 0x61, 0xb4, 0xa6, 0x0e, 0xf6, 0xc3, 0x28, 0xe0, 0x01, 0x51, 0x42, 0xdb, 0x38, 0x76, 0x3c,
	0xbe, 0x09, 0x91, 0x09, 0xc8, 0xfc, 0x05, 0xad, 0x07, 0x7c, 0x1a, 0x79, 0x14, 0x7d, 0x3e, 0xc1,
	0x3f, 0x2b, 0x64, 0x9c, 0x10, 0xd8, 0xf7, 0xad, 0x25, 0xea, 0xb5, 0x6e, 0xad, 0xd7, 0x98, 0x24,
	0xdf, 0xc4, 0x80, 0xba, 0x4d, 0x23, 0xbe, 0x70, 0xad, 0x8d, 0xae, 0x74, 0x6b, 0x3d, 0x75, 0x92,
	0xad, 0x89, 0x06, 0x07, 0xcc, 0x09, 0x22, 0xd4, 0xd5, 0xa4, 0x20, 0x16, 0xe6, 0x05, 0xb4, 0x73,
	0xca, 0x2c, 0x0c, 0x7c, 0x86, 0xe4, 0x04, 0x14, 0xea, 0x4a, 0x61, 0x85, 0xba, 0xe6, 0xbf, 0x1a,
	0x74, 0x7e, 0xae, 0x30, 0xda, 0x08, 0x1e, 0x4b, 0x2d, 0xbc, 0xce, 0x78, 0x87, 0xc3, 0xe3, 0x7e,
	0x68, 0xf7, 0x1f, 0x43, 0x3e, 0xe5, 0x11, 0xf5, 0xe7, 0xf1, 0x36, 0xf2, 0x46, 0x3a, 0x54, 0xaa,
	0x08, 0xc2, 0xf0, 0xdb, 0x9c, 0x61, 0x75, 0x4b, 0xbb, 0xf7, 0xf9, 0xa7, 0x0f, 0xa3, 0x60, 0x19,
	0xe6, 0xfc, 0x5f, 0xa4, 0xfe, 0xf7, 0xab, 0x78, 0xa2, 0x46, 0xde, 0x01, 0x38, 0x11, 0x5a, 0x1c,
	0xdd, 0x99, 0xc5, 0xf5, 0x83, 0x2a, 0x66, 0x43, 0x12, 0xee, 0xb8, 0xd9, 0x03, 0x6d, 0x77, 0x2c,
	0x39, 0x7f, 0x0b, 0x54, 0xea, 0x32, 0xbd, 0xd6, 0x55, 0x7b, 0x8d, 0x49, 0xfc, 0x69, 0x5e, 0x41,
	0xfb, 0x1b, 0xf2, 0xc2, 0xf8, 0x65, 0xda, 0x2d, 0x90, 0x3c, 0x4d, 0xca, 0x5d, 0xc2, 0x73, 0x47,
	0x40, 0x09, 0xf7, 0x70, 0x08, 0xb1, 0x23, 0x79, 0xe6, 0x69, 0xc9, 0xbc, 0x82, 0xce, 0x18, 0x3d,
	0xe4, 0xb8, 0x7b, 0xcd, 0xc5, 0xbb, 0x38, 0x05, 0x6d, 0x97, 0x26, 0x9a, 0x98, 0x2f, 0xe1, 0x4c,
	0xe0, 0x77, 0x9e, 0xb7, 0xeb, 0xd3, 0x34, 0x40, 0x2f, 0x97, 0xe4, 0xb6, 0x31, 0x34, 0x1f, 0xf0,
	0xe9, 0xbb, 0xc5, 0x9d, 0x45, 0xda, 0xf1, 0x1c, 0x1a, 0xc2, 0xd3, 0x2c, 0x6b, 0x5c, 0x17, 0xc0,
	0xbd, 0xbb, 0x4d, 0x91, 0x92, 0x4f, 0x91, 0x99, 0xe4, 0x53, 0xaa, 0x94, 0x42, 0xa4, 0x26, 0xc6,
	0x7f, 0xc0, 0xe1, 0x34, 0x88, 0xb2, 0xb9, 0x34, 0x38, 0xa0, 0x1c, 0x97, 0xe9, 0xf1, 0x89, 0x05,
	0xb9, 0x86, 0x76, 0x84, 0xcb, 0x60, 0x8d, 0x33, 0x77, 0x15, 0x7a, 0xd4, 0xb1, 0x38, 0xb2, 0xa4,
	0x55, 0x7d, 0xd2, 0x12, 0x85, 0x71, 0x86, 0x9b, 0x97, 0x70, 0x24, 0x14, 0x65, 0xc7, 0x4a, 0xc9,
	0xe1, 0x5f, 0x15, 0x4e, 0xe4, 0xd4, 0x53, 0xf1, 0xce, 0xc8, 0x2d, 0x34, 0xb2, 0xd0, 0x13, 0x2d,
	0xbe, 0x8c, 0xe2, 0xeb, 0x32, 0x5e, 0x14, 0x50, 0x79, 0x5c, 0x7b, 0x64, 0x04, 0x47, 0xf9, 0xcc,
	0x90, 0xb3, 0x98, 0x58, 0xf1, 0x38, 0x0c, 0xbd, 0x5c, 0xc8, 0x44, 0xbe, 0x00, 0x6c, 0x73, 0x42,
	0x92, 0x5e, 0xa5, 0x78, 0x19, 0xa7, 0x45, 0x38, 0xef, 0x21, 0x9f, 0x01, 0xe1, 0xa1, 0x22, 0x3c,
	0xc2, 0x43, 0x65, 0x5c, 0xf6, 0xc8, 0x23, 0xb4, 0x8a, 0xa9, 0x20, 0xe7, 0x5b, 0x7e, 0x29, 0x46,
	0xc6, 0xab, 0xea, 0x62, 0x26, 0xf8, 0x19, 0xea, 0x69, 0x08, 0x48, 0x47, 0x1e, 0x5f, 0x3e, 0x58,
	0x86, 0xb6, 0x0b, 0x66, 0x1b, 0xaf, 0x61, 0x3f, 0xbe, 0x47, 0xd2, 0x8c, 0xeb, 0xb9, 0x8c, 0x18,
	0xad, 0x2d, 0x90, 0x92, 0xbf, 0x7e, 0xfc, 0x7d, 0x33, 0xa7, 0x7c, 0xb1, 0xb2, 0xfb, 0x4e, 0xb0,
	0x1c, 0x84, 0xe8, 0x52, 0x37, 0x08, 0xad, 0x79, 0x30, 0xe0, 0x91, 0x45, 0x7d, 0xea, 0xcf, 0xd9,
	0xda, 0x79, 0x2f, 0xdf, 0xd4, 0x20, 0xf9, 0x7b, 0xb2, 0x41, 0x68, 0xdb, 0xcf, 0x92, 0xcf, 0x9b,
	0xff, 0x01, 0x00, 0x00, 0xff, 0xff, 0x38, 0x25, 0x76, 0xd1, 0x6e, 0x05, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// ClientsServiceClient is the client API for ClientsService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ClientsServiceClient interface {
	NewClient(ctx context.Context, in *NewClientRequest, opts ...grpc.CallOption) (*NewClientResponse, error)
	QueryClients(ctx context.Context, in *QueryClientsRequest, opts ...grpc.CallOption) (*QueryClientsResponse, error)
	GetClients(ctx context.Context, in *GetClientsRequest, opts ...grpc.CallOption) (*GetClientsResponse, error)
	DeleteClient(ctx context.Context, in *DeleteClientRequest, opts ...grpc.CallOption) (*DeleteClientResponse, error)
	DeleteAllClients(ctx context.Context, in *DeleteAllClientsRequest, opts ...grpc.CallOption) (*DeleteAllClientsResponse, error)
	NewMatch(ctx context.Context, in *NewMatchRequest, opts ...grpc.CallOption) (*NewMatchResponse, error)
	Sort(ctx context.Context, in *SortRequest, opts ...grpc.CallOption) (*SortResponse, error)
}

type clientsServiceClient struct {
	cc *grpc.ClientConn
}

func NewClientsServiceClient(cc *grpc.ClientConn) ClientsServiceClient {
	return &clientsServiceClient{cc}
}

func (c *clientsServiceClient) NewClient(ctx context.Context, in *NewClientRequest, opts ...grpc.CallOption) (*NewClientResponse, error) {
	out := new(NewClientResponse)
	err := c.cc.Invoke(ctx, "/pb.ClientsService/NewClient", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *clientsServiceClient) QueryClients(ctx context.Context, in *QueryClientsRequest, opts ...grpc.CallOption) (*QueryClientsResponse, error) {
	out := new(QueryClientsResponse)
	err := c.cc.Invoke(ctx, "/pb.ClientsService/QueryClients", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *clientsServiceClient) GetClients(ctx context.Context, in *GetClientsRequest, opts ...grpc.CallOption) (*GetClientsResponse, error) {
	out := new(GetClientsResponse)
	err := c.cc.Invoke(ctx, "/pb.ClientsService/GetClients", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *clientsServiceClient) DeleteClient(ctx context.Context, in *DeleteClientRequest, opts ...grpc.CallOption) (*DeleteClientResponse, error) {
	out := new(DeleteClientResponse)
	err := c.cc.Invoke(ctx, "/pb.ClientsService/DeleteClient", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *clientsServiceClient) DeleteAllClients(ctx context.Context, in *DeleteAllClientsRequest, opts ...grpc.CallOption) (*DeleteAllClientsResponse, error) {
	out := new(DeleteAllClientsResponse)
	err := c.cc.Invoke(ctx, "/pb.ClientsService/DeleteAllClients", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *clientsServiceClient) NewMatch(ctx context.Context, in *NewMatchRequest, opts ...grpc.CallOption) (*NewMatchResponse, error) {
	out := new(NewMatchResponse)
	err := c.cc.Invoke(ctx, "/pb.ClientsService/NewMatch", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *clientsServiceClient) Sort(ctx context.Context, in *SortRequest, opts ...grpc.CallOption) (*SortResponse, error) {
	out := new(SortResponse)
	err := c.cc.Invoke(ctx, "/pb.ClientsService/Sort", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ClientsServiceServer is the server API for ClientsService service.
type ClientsServiceServer interface {
	NewClient(context.Context, *NewClientRequest) (*NewClientResponse, error)
	QueryClients(context.Context, *QueryClientsRequest) (*QueryClientsResponse, error)
	GetClients(context.Context, *GetClientsRequest) (*GetClientsResponse, error)
	DeleteClient(context.Context, *DeleteClientRequest) (*DeleteClientResponse, error)
	DeleteAllClients(context.Context, *DeleteAllClientsRequest) (*DeleteAllClientsResponse, error)
	NewMatch(context.Context, *NewMatchRequest) (*NewMatchResponse, error)
	Sort(context.Context, *SortRequest) (*SortResponse, error)
}

// UnimplementedClientsServiceServer can be embedded to have forward compatible implementations.
type UnimplementedClientsServiceServer struct {
}

func (*UnimplementedClientsServiceServer) NewClient(ctx context.Context, req *NewClientRequest) (*NewClientResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method NewClient not implemented")
}
func (*UnimplementedClientsServiceServer) QueryClients(ctx context.Context, req *QueryClientsRequest) (*QueryClientsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method QueryClients not implemented")
}
func (*UnimplementedClientsServiceServer) GetClients(ctx context.Context, req *GetClientsRequest) (*GetClientsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetClients not implemented")
}
func (*UnimplementedClientsServiceServer) DeleteClient(ctx context.Context, req *DeleteClientRequest) (*DeleteClientResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteClient not implemented")
}
func (*UnimplementedClientsServiceServer) DeleteAllClients(ctx context.Context, req *DeleteAllClientsRequest) (*DeleteAllClientsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteAllClients not implemented")
}
func (*UnimplementedClientsServiceServer) NewMatch(ctx context.Context, req *NewMatchRequest) (*NewMatchResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method NewMatch not implemented")
}
func (*UnimplementedClientsServiceServer) Sort(ctx context.Context, req *SortRequest) (*SortResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Sort not implemented")
}

func RegisterClientsServiceServer(s *grpc.Server, srv ClientsServiceServer) {
	s.RegisterService(&_ClientsService_serviceDesc, srv)
}

func _ClientsService_NewClient_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NewClientRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClientsServiceServer).NewClient(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.ClientsService/NewClient",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClientsServiceServer).NewClient(ctx, req.(*NewClientRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ClientsService_QueryClients_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryClientsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClientsServiceServer).QueryClients(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.ClientsService/QueryClients",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClientsServiceServer).QueryClients(ctx, req.(*QueryClientsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ClientsService_GetClients_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetClientsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClientsServiceServer).GetClients(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.ClientsService/GetClients",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClientsServiceServer).GetClients(ctx, req.(*GetClientsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ClientsService_DeleteClient_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteClientRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClientsServiceServer).DeleteClient(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.ClientsService/DeleteClient",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClientsServiceServer).DeleteClient(ctx, req.(*DeleteClientRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ClientsService_DeleteAllClients_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteAllClientsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClientsServiceServer).DeleteAllClients(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.ClientsService/DeleteAllClients",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClientsServiceServer).DeleteAllClients(ctx, req.(*DeleteAllClientsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ClientsService_NewMatch_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NewMatchRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClientsServiceServer).NewMatch(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.ClientsService/NewMatch",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClientsServiceServer).NewMatch(ctx, req.(*NewMatchRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ClientsService_Sort_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SortRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClientsServiceServer).Sort(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.ClientsService/Sort",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClientsServiceServer).Sort(ctx, req.(*SortRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _ClientsService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "pb.ClientsService",
	HandlerType: (*ClientsServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "NewClient",
			Handler:    _ClientsService_NewClient_Handler,
		},
		{
			MethodName: "QueryClients",
			Handler:    _ClientsService_QueryClients_Handler,
		},
		{
			MethodName: "GetClients",
			Handler:    _ClientsService_GetClients_Handler,
		},
		{
			MethodName: "DeleteClient",
			Handler:    _ClientsService_DeleteClient_Handler,
		},
		{
			MethodName: "DeleteAllClients",
			Handler:    _ClientsService_DeleteAllClients_Handler,
		},
		{
			MethodName: "NewMatch",
			Handler:    _ClientsService_NewMatch_Handler,
		},
		{
			MethodName: "Sort",
			Handler:    _ClientsService_Sort_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "clservice.proto",
}
