// Code generated by protoc-gen-go. DO NOT EDIT.
// source: cltypes.proto

package pb

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Client struct {
	Id       string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name     string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Birthday int64  `protobuf:"varint,3,opt,name=birthday,proto3" json:"birthday,omitempty"`
	Score    int64  `protobuf:"varint,4,opt,name=score,proto3" json:"score,omitempty"`
	CreatedAt            int64    `protobuf:"varint,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Client) Reset()         { *m = Client{} }
func (m *Client) String() string { return proto.CompactTextString(m) }
func (*Client) ProtoMessage()    {}
func (*Client) Descriptor() ([]byte, []int) {
	return fileDescriptor_597723fcca9cabf3, []int{0}
}

func (m *Client) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Client.Unmarshal(m, b)
}
func (m *Client) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Client.Marshal(b, m, deterministic)
}
func (m *Client) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Client.Merge(m, src)
}
func (m *Client) XXX_Size() int {
	return xxx_messageInfo_Client.Size(m)
}
func (m *Client) XXX_DiscardUnknown() {
	xxx_messageInfo_Client.DiscardUnknown(m)
}

var xxx_messageInfo_Client proto.InternalMessageInfo

func (m *Client) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Client) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Client) GetBirthday() int64 {
	if m != nil {
		return m.Birthday
	}
	return 0
}

func (m *Client) GetScore() int64 {
	if m != nil {
		return m.Score
	}
	return 0
}

func (m *Client) GetCreatedAt() int64 {
	if m != nil {
		return m.CreatedAt
	}
	return 0
}

type OptInt64 struct {
	Value                int64    `protobuf:"varint,1,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *OptInt64) Reset()         { *m = OptInt64{} }
func (m *OptInt64) String() string { return proto.CompactTextString(m) }
func (*OptInt64) ProtoMessage()    {}
func (*OptInt64) Descriptor() ([]byte, []int) {
	return fileDescriptor_597723fcca9cabf3, []int{1}
}

func (m *OptInt64) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OptInt64.Unmarshal(m, b)
}
func (m *OptInt64) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OptInt64.Marshal(b, m, deterministic)
}
func (m *OptInt64) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OptInt64.Merge(m, src)
}
func (m *OptInt64) XXX_Size() int {
	return xxx_messageInfo_OptInt64.Size(m)
}
func (m *OptInt64) XXX_DiscardUnknown() {
	xxx_messageInfo_OptInt64.DiscardUnknown(m)
}

var xxx_messageInfo_OptInt64 proto.InternalMessageInfo

func (m *OptInt64) GetValue() int64 {
	if m != nil {
		return m.Value
	}
	return 0
}

type OptString struct {
	Value                string   `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *OptString) Reset()         { *m = OptString{} }
func (m *OptString) String() string { return proto.CompactTextString(m) }
func (*OptString) ProtoMessage()    {}
func (*OptString) Descriptor() ([]byte, []int) {
	return fileDescriptor_597723fcca9cabf3, []int{2}
}

func (m *OptString) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OptString.Unmarshal(m, b)
}
func (m *OptString) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OptString.Marshal(b, m, deterministic)
}
func (m *OptString) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OptString.Merge(m, src)
}
func (m *OptString) XXX_Size() int {
	return xxx_messageInfo_OptString.Size(m)
}
func (m *OptString) XXX_DiscardUnknown() {
	xxx_messageInfo_OptString.DiscardUnknown(m)
}

var xxx_messageInfo_OptString proto.InternalMessageInfo

func (m *OptString) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

type Int64Comp struct {
	Value                int64    `protobuf:"varint,1,opt,name=value,proto3" json:"value,omitempty"`
	Op                   string   `protobuf:"bytes,2,opt,name=op,proto3" json:"op,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Int64Comp) Reset()         { *m = Int64Comp{} }
func (m *Int64Comp) String() string { return proto.CompactTextString(m) }
func (*Int64Comp) ProtoMessage()    {}
func (*Int64Comp) Descriptor() ([]byte, []int) {
	return fileDescriptor_597723fcca9cabf3, []int{3}
}

func (m *Int64Comp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Int64Comp.Unmarshal(m, b)
}
func (m *Int64Comp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Int64Comp.Marshal(b, m, deterministic)
}
func (m *Int64Comp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Int64Comp.Merge(m, src)
}
func (m *Int64Comp) XXX_Size() int {
	return xxx_messageInfo_Int64Comp.Size(m)
}
func (m *Int64Comp) XXX_DiscardUnknown() {
	xxx_messageInfo_Int64Comp.DiscardUnknown(m)
}

var xxx_messageInfo_Int64Comp proto.InternalMessageInfo

func (m *Int64Comp) GetValue() int64 {
	if m != nil {
		return m.Value
	}
	return 0
}

func (m *Int64Comp) GetOp() string {
	if m != nil {
		return m.Op
	}
	return ""
}

func init() {
	proto.RegisterType((*Client)(nil), "pb.Client")
	proto.RegisterType((*OptInt64)(nil), "pb.OptInt64")
	proto.RegisterType((*OptString)(nil), "pb.OptString")
	proto.RegisterType((*Int64Comp)(nil), "pb.Int64Comp")
}

func init() { proto.RegisterFile("cltypes.proto", fileDescriptor_597723fcca9cabf3) }

var fileDescriptor_597723fcca9cabf3 = []byte{
	// 245 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x50, 0x3d, 0x4b, 0x03, 0x41,
	0x10, 0xe5, 0xee, 0x92, 0x90, 0x1d, 0xd0, 0x62, 0xb1, 0x58, 0x04, 0xe1, 0xbc, 0x2a, 0x8d, 0x39,
	0x24, 0x6a, 0xaf, 0xa9, 0xac, 0x02, 0x67, 0x67, 0x23, 0xfb, 0xc5, 0x65, 0xe1, 0x6e, 0x77, 0xd8,
	0x9d, 0x04, 0x52, 0xf8, 0xdf, 0x25, 0x9b, 0x28, 0x08, 0xe9, 0xe6, 0x7d, 0xf0, 0x98, 0xf7, 0xe0,
	0x4a, 0x0f, 0x74, 0x40, 0x9b, 0x96, 0x18, 0x03, 0x05, 0x5e, 0xa2, 0x6a, 0xbe, 0x61, 0xb6, 0x1e,
	0x9c, 0xf5, 0xc4, 0xaf, 0xa1, 0x74, 0x46, 0x14, 0x75, 0xb1, 0x60, 0x5d, 0xe9, 0x0c, 0xe7, 0x30,
	0xf1, 0x72, 0xb4, 0xa2, 0xcc, 0x4c, 0xbe, 0xf9, 0x2d, 0xcc, 0x95, 0x8b, 0xb4, 0x35, 0xf2, 0x20,
	0xaa, 0xba, 0x58, 0x54, 0xdd, 0x1f, 0xe6, 0x37, 0x30, 0x4d, 0x3a, 0x44, 0x2b, 0x26, 0x59, 0x38,
	0x01, 0x7e, 0x07, 0xa0, 0xa3, 0x95, 0x64, 0xcd, 0x97, 0x24, 0x31, 0xcd, 0x12, 0x3b, 0x33, 0xaf,
	0xd4, 0xd4, 0x30, 0xdf, 0x20, 0xbd, 0x7b, 0x7a, 0x79, 0x3a, 0x06, 0xec, 0xe5, 0xb0, 0xb3, 0xf9,
	0x87, 0xaa, 0x3b, 0x81, 0xe6, 0x1e, 0xd8, 0x06, 0xe9, 0x83, 0xa2, 0xf3, 0xfd, 0x7f, 0x0b, 0xfb,
	0xb5, 0x3c, 0x02, 0xcb, 0x09, 0xeb, 0x30, 0xe2, 0xe5, 0x94, 0x63, 0xb9, 0x80, 0xe7, 0x2a, 0x65,
	0xc0, 0xb7, 0xe7, 0xcf, 0x55, 0xef, 0x68, 0xbb, 0x53, 0x4b, 0x1d, 0xc6, 0x16, 0xad, 0x71, 0x26,
	0xa0, 0xec, 0x43, 0x4b, 0x51, 0x3a, 0xef, 0x7c, 0x9f, 0xf6, 0xfa, 0x41, 0xe7, 0x61, 0x52, 0x9b,
	0xd7, 0x4a, 0x2d, 0x2a, 0x35, 0xcb, 0xe7, 0xea, 0x27, 0x00, 0x00, 0xff, 0xff, 0xd1, 0xc5, 0x70,
	0xd2, 0x49, 0x01, 0x00, 0x00,
}
